#!/usr/bin/env bash
#
# Regenerate the "Available skills" table in _base/README.md from the active
# skills enumerated in `.claude-plugin/plugin.json`. The manifest is generated
# from `.agents/skills.enabled.json` and `.agents/skill-library.json`.
#
# The script preserves everything outside the markers:
#
#   <!-- BEGIN skills-table -->
#   ...generated content...
#   <!-- END skills-table -->
#
# For each skill, the row description comes from:
#   1. the matching Claude wrapper's frontmatter `description:` (preferred — it's
#      the same one-line summary users see when invoking the skill), or
#   2. the first non-heading paragraph under `## Purpose` in the playbook, or
#   3. "(no description)" as a last resort.

set -euo pipefail

readonly VERSION="0.2.0"

usage() {
  cat <<'EOF'
Usage: gen-skills-table.sh [OPTION]

Regenerate the "Available skills" table in _base/README.md from the active
skills listed in .claude-plugin/plugin.json.

With no option, regenerate the table in place.

Options:
  --check      Validate that the table is current without writing files.
  --version    Print version and exit.
  --help       Show this message and exit.
EOF
}

CHECK_MODE=0
case "${1:-}" in
  --version) printf 'gen-skills-table.sh %s\n' "$VERSION"; exit 0 ;;
  --help)    usage; exit 0 ;;
  --check)   CHECK_MODE=1 ;;
  "")        ;;
  *)         printf 'unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
esac

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
README="$REPO_ROOT/_base/README.md"
MANIFEST="$REPO_ROOT/.claude-plugin/plugin.json"
PLAYBOOKS_DIR="$REPO_ROOT/playbooks/skills"
CLAUDE_SKILLS_DIR="$REPO_ROOT/.claude/skills"

BEGIN_MARKER='<!-- BEGIN skills-table -->'
END_MARKER='<!-- END skills-table -->'

if [[ ! -f "$README" ]]; then
  echo "error: $README not found" >&2
  exit 1
fi

if [[ ! -f "$MANIFEST" ]]; then
  echo "error: $MANIFEST not found" >&2
  exit 1
fi

if ! grep -qF "$BEGIN_MARKER" "$README" || ! grep -qF "$END_MARKER" "$README"; then
  echo "error: $README is missing the BEGIN/END skills-table markers" >&2
  exit 1
fi

# Read the manifest into a name-sorted list of "name<TAB>bucket" pairs.
mapfile -t SKILL_TUPLES < <(python3 - "$MANIFEST" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
pairs = []
for p in data["skills"]:
    parts = p.strip("./").split("/")
    if len(parts) != 3 or parts[0] != "skills":
        sys.exit(f"manifest entry malformed: {p}")
    pairs.append((parts[2], parts[1]))
for name, bucket in sorted(pairs):
    print(f"{name}\t{bucket}")
PY
)

# Extract one-line description for a skill.
description_for() {
  local name="$1" bucket="$2"
  local wrapper="$CLAUDE_SKILLS_DIR/$bucket/$name/SKILL.md"
  local playbook="$PLAYBOOKS_DIR/$bucket/$name.md"

  if [[ -f "$wrapper" ]]; then
    local desc
    desc=$(python3 - "$wrapper" <<'PY'
import json, sys

path = sys.argv[1]
in_frontmatter = False
with open(path) as f:
    for raw in f:
        line = raw.rstrip("\n")
        if line.strip() == "---":
            if in_frontmatter:
                break
            in_frontmatter = True
            continue
        if not in_frontmatter:
            continue
        if line.startswith("description:"):
            value = line.split(":", 1)[1].strip()
            if len(value) >= 2 and value[0] == value[-1] == '"':
                try:
                    value = json.loads(value)
                except json.JSONDecodeError:
                    value = value[1:-1]
            elif len(value) >= 2 and value[0] == value[-1] == "'":
                value = value[1:-1].replace("''", "'")
            print(value)
            break
PY
)
    if [[ -n "$desc" ]]; then
      printf '%s' "$desc"
      return
    fi
  fi

  if [[ -f "$playbook" ]]; then
    local purpose
    purpose=$(awk '
      /^## Purpose/ { in_section = 1; next }
      in_section && /^## / { exit }
      in_section && NF { print; exit }
    ' "$playbook")
    if [[ -n "$purpose" ]]; then
      printf '%s' "$purpose"
      return
    fi
  fi

  printf '(no description)'
}

# Build the new table body.
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "$BEGIN_MARKER"
  echo "<!-- This block is auto-generated by _base/scripts/gen-skills-table.sh from .claude-plugin/plugin.json — do not edit by hand. -->"
  echo
  echo "| Skill | Bucket | Description |"
  echo "|-------|--------|-------------|"
  for tuple in "${SKILL_TUPLES[@]}"; do
    name="${tuple%%	*}"
    bucket="${tuple##*	}"
    desc=$(description_for "$name" "$bucket")
    desc=${desc//|/\\|}
    printf '| %s | %s | %s |\n' "$name" "$bucket" "$desc"
  done
  echo
  echo "$END_MARKER"
} > "$TMP"

# Splice the new block into _base/README.md in place.
python3 - "$README" "$TMP" "$BEGIN_MARKER" "$END_MARKER" "$CHECK_MODE" <<'PY'
import sys, pathlib

readme_path, new_block_path, begin, end, check_mode = sys.argv[1:6]
readme = pathlib.Path(readme_path).read_text()
new_block = pathlib.Path(new_block_path).read_text().rstrip("\n")

start = readme.index(begin)
stop = readme.index(end) + len(end)
updated = readme[:start] + new_block + readme[stop:]

if updated != readme:
    if check_mode == "1":
        print(f"out of date ({readme_path})")
        sys.exit(1)
    pathlib.Path(readme_path).write_text(updated)
    print(f"updated {readme_path}")
else:
    print(f"no changes ({readme_path})")
PY
