#!/usr/bin/env bash
#
# Install (or verify) the local, opt-in pre-commit hook that runs
# _base/scripts/check-template-update.sh and _base/scripts/tests/test-hooks.sh
# before every commit in this checkout.
#
# Not wired into setup-agents.sh: installing this hook is a deliberate,
# per-repo choice, since it changes commit behavior (it can block a commit).

set -euo pipefail

MODE="write"

usage() {
  cat <<'EOF'
Usage: _base/scripts/install-git-hooks.sh [--check]

Install or verify the local pre-commit template-verification hook.

What it manages:
  - .git/hooks/pre-commit — a generated wrapper that execs the tracked
    _base/scripts/git-hooks/pre-commit script

The hook runs _base/scripts/check-template-update.sh and
_base/scripts/tests/test-hooks.sh before each commit, and blocks the commit if
either fails. Bypass in an emergency with: git commit --no-verify

Options:
  --check   Verify only; do not write .git/hooks/pre-commit.
  --help    Show this message.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      MODE="check"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      printf 'unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

HOOK_BODY_RELATIVE="_base/scripts/git-hooks/pre-commit"
HOOK_TARGET="${REPO_ROOT}/.git/hooks/pre-commit"

read -r -d '' EXPECTED_HOOK <<EOF || true
#!/bin/sh
# Generated by _base/scripts/install-git-hooks.sh. Do not edit directly —
# edit ${HOOK_BODY_RELATIVE} instead, then re-run the installer.
exec "\$(git rev-parse --show-toplevel)/${HOOK_BODY_RELATIVE}" "\$@"
EOF

if [[ "${MODE}" == "check" ]]; then
  if [[ ! -f "${HOOK_TARGET}" ]]; then
    printf 'SKIP  local pre-commit hook is not installed (run ./_base/scripts/install-git-hooks.sh to enable it)\n'
    exit 0
  fi

  if [[ ! -x "${HOOK_TARGET}" ]]; then
    printf 'FAIL  .git/hooks/pre-commit exists but is not executable\n' >&2
    exit 1
  fi

  if ! grep -qF "${HOOK_BODY_RELATIVE}" "${HOOK_TARGET}"; then
    printf 'FAIL  .git/hooks/pre-commit exists but does not invoke %s\n' "${HOOK_BODY_RELATIVE}" >&2
    printf '      Run ./_base/scripts/install-git-hooks.sh to reinstall it.\n' >&2
    exit 1
  fi

  printf 'OK  local pre-commit hook is installed\n'
  exit 0
fi

git -C "${REPO_ROOT}" rev-parse --git-dir >/dev/null

if [[ -e "${HOOK_TARGET}" ]] && ! grep -qF "${HOOK_BODY_RELATIVE}" "${HOOK_TARGET}" 2>/dev/null; then
  printf 'error: .git/hooks/pre-commit already exists and was not installed by this script.\n' >&2
  printf '       Reconcile it by hand (merge its logic into %s or move it aside), then re-run.\n' "${HOOK_BODY_RELATIVE}" >&2
  exit 1
fi

mkdir -p "$(dirname "${HOOK_TARGET}")"
printf '%s\n' "${EXPECTED_HOOK}" > "${HOOK_TARGET}"
chmod +x "${HOOK_TARGET}"

cat <<EOF
Local pre-commit hook installed at .git/hooks/pre-commit.

It runs _base/scripts/check-template-update.sh and
_base/scripts/tests/test-hooks.sh before each commit, and blocks the commit if
either fails. Bypass in an emergency with: git commit --no-verify
EOF
