#!/usr/bin/env python3
"""Regenerate task ledgers and generated area status blocks from task files.

Vendored under the `task-ledger` skill; invoked via `at ledger sync` / `at ledger
check` / `at ledger rotate-log <TASK-ID>` (see `plugins/agents-tasks/bin/at-ledger`).
The behavior, CLI flags, ``--check`` strict/permissive semantics, output text, and
marker-delimited generated blocks are preserved from the historical shell
implementation; the port additionally fixes two long-standing defects by
construction:

- Titles are rendered verbatim: the old shell pipeline ran generated rows
  through ``printf '%b'``, which expanded backslash escapes (``\\t``, ``\\n``,
  Windows paths) inside task titles and corrupted the ledgers.
- Table metadata is parsed with the shared escape-aware splitter in
  ``mdtables.py`` (the same one ``check_repos_config.sh`` uses), so an
  escaped pipe (``\\|``) in a cell is understood instead of mis-split.

Sources of truth:
  docs/tasks_manager/_areas.md
  docs/tasks_manager/_roadmap.md
  docs/tasks_manager/_todos/*.md
  docs/tasks_manager/_todos_archived/*.md

Generated outputs:
  docs/tasks_manager/_active.md
  docs/tasks_manager/_done.md
  docs/areas/_overview.md
  marker-delimited blocks in docs/areas/<slug>.md
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mdtables  # noqa: E402


USAGE = """Usage: sync_todo_ledgers.py [--check] [--root DIR] [rotate-log TASK_ID]

Regenerate task ledgers and generated area status blocks. Normally invoked via
`at ledger sync`, `at ledger check`, or `at ledger rotate-log <TASK_ID>`.

Options:
  --check        Validate strictly without writing files.
  --root DIR     Repository root (default: git toplevel of the current directory,
                 else the current directory).
  --help         Show this message.

Commands:
  rotate-log TASK_ID   Move TASK_ID's `## Execution log` body into
                        docs/tasks_manager/_logs/<TASK_ID>.md, leaving a short
                        pointer in the task file.
"""

AREA_STATUS_BEGIN = "<!-- BEGIN generated-area-status -->"
AREA_STATUS_END = "<!-- END generated-area-status -->"
AREA_OVERVIEW_BEGIN = "<!-- BEGIN generated-area-overview -->"
AREA_OVERVIEW_END = "<!-- END generated-area-overview -->"

# The block-embedded note text. Old ledgers synced by the historical shell/older
# python tooling carry OLD_GENERATED_NOTE; --check accepts that as equivalent to
# the current text so a rename alone doesn't make every downstream ledger "stale"
# (see write_or_check).
OLD_GENERATED_NOTE = (
    "_Generated by `_base/scripts/sync-todo-ledgers.sh`. Do not edit this block by hand._"
)
GENERATED_NOTE = "_Generated by `at ledger sync`. Do not edit this block by hand._"

# Same idea for the ledger headers' "rebuild with ..." line.
OLD_SYNC_REF = "`_base/scripts/sync-todo-ledgers.sh`"
SYNC_REF = "`at ledger sync`"

ACTIVE_HEADER = """# Active tasks

Ledger of every `open` and `in_progress` task - the backlog view. Sorted in_progress first, then by
priority, then Task ID. Rows are maintained as tasks change status; rebuild any time with
`at ledger sync`. The task files in `docs/tasks_manager/_todos/` remain the source of truth.

| Task ID | Type | Title | Area | Status | Priority | Phase | Updated | File |
|---------|------|-------|------|--------|----------|-------|---------|------|"""

DONE_HEADER = """# Done tasks

Ledger of completed and cancelled tasks. Newest row at the top. Rebuild any time with
`at ledger sync`.

| Task ID | Type | Title | Area | Completed | Commit | File |
|---------|------|-------|------|-----------|--------|------|"""

# Metadata keys recognized in a task's leading table (lowercased key -> field name).
TASK_META_KEYS = {
    "task id": "taskid",
    "type": "type",
    "area": "area",
    "created": "created",
    "updated": "updated",
    "last executed": "last_executed",
    "status": "status",
    "priority": "priority",
    "owner": "owner",
    "blocked by": "blocked_by",
    "source": "source",
    "source ref": "source_ref",
    "target date": "target_date",
    "deadline": "deadline",
}

DATETIME_PREFIX = r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}(:[0-9]{2})?"
DATE_FULL = r"^[0-9]{4}-[0-9]{2}-[0-9]{2}$"


@dataclass
class TaskRecord:
    taskid: str = ""
    type: str = ""
    area: str = ""
    created: str = ""
    updated: str = ""
    last_executed: str = ""
    status: str = ""
    priority: str = ""
    owner: str = ""
    blocked_by: str = ""
    source: str = ""
    source_ref: str = ""
    target_date: str = ""
    deadline: str = ""
    title: str = ""
    done: int = 0
    total: int = 0


def md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").split("\n")


class Generator:
    def __init__(self, repo_root: Path, check_mode: bool) -> None:
        self.repo_root = repo_root
        self.check_mode = check_mode
        self.check_errors = 0

        docs = repo_root / "docs"
        self.tm = docs / "tasks_manager"
        self.todos = self.tm / "_todos"
        self.archived = self.tm / "_todos_archived"
        self.inbox = self.tm / "_inbox"
        self.inbox_archived = self.tm / "_inbox_archived"
        self.areas_file = self.tm / "_areas.md"
        self.roadmap = self.tm / "_roadmap.md"
        self.active_ledger = self.tm / "_active.md"
        self.done_ledger = self.tm / "_done.md"
        self.areas_dir = docs / "areas"
        self.areas_overview = self.areas_dir / "_overview.md"

        # Area registry state.
        self.area_prefix: dict[str, str] = {}
        self.area_desc: dict[str, str] = {}
        self.area_page: dict[str, str] = {}
        self.prefix_area: dict[str, str] = {}
        self.areas: list[str] = []

        # Task state.
        self.task_count: dict[str, int] = {}
        self.task_file: dict[str, Path] = {}
        self.task_base: dict[str, str] = {}
        self.task_dir: dict[str, str] = {}
        self.task_type: dict[str, str] = {}
        self.task_area: dict[str, str] = {}
        self.task_status: dict[str, str] = {}
        self.task_priority: dict[str, str] = {}
        self.task_updated: dict[str, str] = {}
        self.task_title: dict[str, str] = {}
        self.task_phase: dict[str, str] = {}
        self.task_ids: list[str] = []

        # Per-area status counters.
        self.area_open: dict[str, int] = {}
        self.area_inprogress: dict[str, int] = {}
        self.area_done: dict[str, int] = {}
        self.area_urgent: dict[str, int] = {}
        self.area_now: dict[str, int] = {}
        self.area_next: dict[str, int] = {}
        self.area_later: dict[str, int] = {}
        self.area_someday: dict[str, int] = {}

        # Inbox state.
        self.inbox_count: dict[str, int] = {}
        self.inbox_dir: dict[str, str] = {}
        self.inbox_status: dict[str, str] = {}
        self.inbox_ids: list[str] = []

        # Roadmap state.
        self.roadmap_task_count: dict[str, int] = {}
        self.roadmap_task_horizon: dict[str, str] = {}
        self.roadmap_task_ids: list[str] = []
        self.roadmap_inbox_count: dict[str, int] = {}
        self.roadmap_inbox_horizon: dict[str, str] = {}
        self.roadmap_inbox_ids: list[str] = []

    # ---- diagnostics -----------------------------------------------------

    def rel_repo(self, path: Path | str) -> str:
        text = str(path)
        root = str(self.repo_root) + "/"
        if text.startswith(root):
            return text[len(root):]
        return text

    def warn(self, message: str) -> None:
        print(f"WARNING: {message}", file=sys.stderr)

    def error(self, message: str) -> None:
        print(f"ERROR: {message}", file=sys.stderr)
        self.check_errors += 1

    def validate_or_warn(self, message: str) -> None:
        if self.check_mode:
            self.error(message)
        else:
            self.warn(message)

    def check_only_error(self, message: str) -> None:
        if self.check_mode:
            self.error(message)

    # ---- path helpers ----------------------------------------------------

    def page_abs_for(self, page: str) -> Path:
        if page.startswith("/"):
            candidate = Path(page)
        else:
            candidate = self.tm / page
        return Path(os.path.abspath(candidate.expanduser()))

    def path_abs(self, path: Path | str) -> Path:
        return Path(os.path.abspath(Path(path).expanduser()))

    def page_rel_from_areas(self, page_abs: Path) -> str:
        return os.path.relpath(page_abs, self.path_abs(self.areas_dir))

    # ---- structure -------------------------------------------------------

    def ensure_check_structure(self) -> None:
        checks = [
            (self.todos.is_dir(), f"missing task directory {self.rel_repo(self.todos)}"),
            (self.archived.is_dir(), f"missing archived task directory {self.rel_repo(self.archived)}"),
            (self.inbox.is_dir(), f"missing inbox directory {self.rel_repo(self.inbox)}"),
            (self.inbox_archived.is_dir(), f"missing archived inbox directory {self.rel_repo(self.inbox_archived)}"),
            (self.areas_dir.is_dir(), f"missing areas directory {self.rel_repo(self.areas_dir)}"),
            (self.areas_file.is_file(), f"missing area registry {self.rel_repo(self.areas_file)}"),
            (self.roadmap.is_file(), f"missing roadmap {self.rel_repo(self.roadmap)}"),
            (self.active_ledger.is_file(), f"missing active ledger {self.rel_repo(self.active_ledger)}"),
            (self.done_ledger.is_file(), f"missing done ledger {self.rel_repo(self.done_ledger)}"),
            (self.areas_overview.is_file(), f"missing area overview {self.rel_repo(self.areas_overview)}"),
        ]
        for ok, message in checks:
            if not ok:
                self.check_only_error(message)

    # ---- area registry ---------------------------------------------------

    def read_areas(self) -> None:
        if self.areas_file.is_file():
            for line in read_lines(self.areas_file):
                if not line.startswith("|"):
                    continue
                cells = mdtables.split_table_row(line)
                if not cells:
                    continue
                area = cells[0]
                prefix = cells[1] if len(cells) > 1 else ""
                desc = cells[2] if len(cells) > 2 else ""
                page = cells[3] if len(cells) > 3 else ""

                if area == "" or re.fullmatch(r"-+", area) or area == "Area":
                    continue
                if area == "---":
                    continue

                if prefix == "" or page == "":
                    self.validate_or_warn(
                        f"area row '{area}' is missing Prefix or Page in {self.rel_repo(self.areas_file)}"
                    )
                    continue
                if not re.fullmatch(r"[a-z][a-z0-9-]*", area):
                    self.validate_or_warn(
                        f"area row '{area}' has malformed Area slug in {self.rel_repo(self.areas_file)}"
                    )
                if not re.fullmatch(r"[A-Z][A-Z0-9]*", prefix):
                    self.validate_or_warn(f"area row '{area}' has malformed Prefix '{prefix}'")
                if area in self.area_prefix:
                    self.validate_or_warn(f"duplicate area '{area}' in {self.rel_repo(self.areas_file)}")
                    continue
                if prefix in self.prefix_area:
                    self.validate_or_warn(
                        f"duplicate prefix '{prefix}' for areas '{self.prefix_area[prefix]}' and '{area}'"
                    )
                    continue
                if prefix == "T" and area != "global":
                    self.validate_or_warn(
                        f"prefix 'T' is reserved for area 'global' but is assigned to '{area}'"
                    )
                page_abs = self.page_abs_for(page)
                expected_page = self.path_abs(self.areas_dir / f"{area}.md")
                if page_abs != expected_page:
                    self.validate_or_warn(
                        f"area row '{area}' has Page '{page}', expected docs/areas/{area}.md"
                    )
                self.area_prefix[area] = prefix
                self.area_desc[area] = desc
                self.area_page[area] = page
                self.prefix_area[prefix] = area
                self.areas.append(area)

        if not self.areas:
            if self.check_mode and self.areas_file.is_file():
                self.error(f"area registry {self.rel_repo(self.areas_file)} contains no valid areas")
            self.area_prefix["global"] = "T"
            self.area_desc["global"] = "Default, cross-area, and uncategorized work."
            self.area_page["global"] = "../areas/global.md"
            self.prefix_area["T"] = "global"
            self.areas.append("global")

    # ---- task extraction -------------------------------------------------

    def extract_task(self, path: Path) -> TaskRecord:
        rec = TaskRecord()
        inphase = False
        hasitem = False
        allchecked = True

        def finalize() -> None:
            nonlocal inphase, hasitem, allchecked
            if inphase and hasitem and allchecked:
                rec.done += 1
            inphase = False

        for line in read_lines(path):
            if line.startswith("|"):
                cells = mdtables.split_table_row(line)
                if cells:
                    key = cells[0].lower()
                    val = cells[1] if len(cells) > 1 else ""
                    field_name = TASK_META_KEYS.get(key)
                    if field_name is not None:
                        setattr(rec, field_name, val)
                continue

            if line.startswith("## ") and rec.title == "":
                rec.title = line[3:].strip()

            if line.startswith("#### "):
                finalize()
                rec.total += 1
                inphase = True
                hasitem = False
                allchecked = True
                continue

            if line.startswith("### ") or line.startswith("---") or line.startswith("## "):
                finalize()
                inphase = False

            if inphase and re.match(r"^[ \t\r\f\v]*-[ \t\r\f\v]*\[[ xX]\]", line):
                hasitem = True
                if re.search(r"\[ \]", line):
                    allchecked = False

        finalize()
        return rec

    # ---- completion-archive validation ----------------------------------

    def task_has_nonempty_section(self, text: str, heading: str) -> bool:
        in_section = False
        for line in text.split("\n"):
            if re.fullmatch(rf"##[ \t\r\f\v]+{re.escape(heading)}[ \t\r\f\v]*", line):
                in_section = True
                continue
            if in_section and re.match(r"^##[ \t\r\f\v]+", line):
                break
            if in_section and line.strip() != "":
                return True
        return False

    def validate_completion_archive(self, path: Path, taskid: str) -> None:
        rel = self.rel_repo(path)
        text = path.read_text(encoding="utf-8")

        if not re.search(r"^##[ \t\r\f\v]+Completion harvest[ \t\r\f\v]*$", text, re.MULTILINE):
            self.warn(
                f"archived task '{taskid}' in {rel} is missing a Completion harvest section"
            )
            return
        harvest: dict[str, str] = {}
        for key, value in mdtables.metadata_pairs(text.split("\n")):
            harvest.setdefault(key.lower(), value)

        def field_ok(key: str, pattern: str) -> bool:
            return re.fullmatch(pattern, harvest.get(key, ""), re.IGNORECASE) is not None

        if not field_ok("resource updates", r"None|N/A|docs/resources/.+"):
            self.warn(
                f"archived task '{taskid}' in {rel} is missing explicit Completion harvest Resource updates"
            )
        if not field_ok("area updates", r"None|N/A|docs/areas/.+"):
            self.warn(
                f"archived task '{taskid}' in {rel} is missing explicit Completion harvest Area updates"
            )
        if not field_ok("follow-ups", r"None|N/A|I-[0-9]{3,}.*"):
            self.warn(
                f"archived task '{taskid}' in {rel} is missing explicit Completion harvest Follow-ups"
            )
        if not field_ok("notable decisions/deviations", r"None|N/A|.*[A-Za-z0-9].*"):
            self.warn(
                f"archived task '{taskid}' in {rel} is missing explicit Completion harvest Notable decisions/deviations"
            )
        if not re.search(r"^##[ \t\r\f\v]+Completion summary[ \t\r\f\v]*$", text, re.MULTILINE):
            self.warn(
                f"archived task '{taskid}' in {rel} is missing a Completion summary section"
            )
        elif not self.task_has_nonempty_section(text, "Completion summary"):
            self.warn(
                f"archived task '{taskid}' in {rel} has an empty Completion summary section"
            )

    # ---- task metadata validation ---------------------------------------

    def validate_task_metadata(self, path: Path, base: str, rec: TaskRecord) -> None:
        rel = self.rel_repo(path)

        def missing(label: str, value: str) -> bool:
            if value == "":
                self.validate_or_warn(f"task '{base}' is missing {label}")
                return True
            return False

        required_missing = False
        required_missing |= missing("Task ID", rec.taskid)
        required_missing |= missing("Type", rec.type)
        required_missing |= missing("Area", rec.area)
        required_missing |= missing("Created", rec.created)
        if rec.updated == "" or rec.updated == "N/A":
            self.validate_or_warn(f"task '{base}' is missing Updated")
            required_missing = True
        required_missing |= missing("Status", rec.status)
        required_missing |= missing("Priority", rec.priority)
        required_missing |= missing("Source", rec.source)
        # Last executed, Owner, Blocked by, and Source ref are optional metadata:
        # not required, but still format-checked below when present.
        if rec.title == "":
            self.validate_or_warn(f"task '{base}' in {rel} is missing a title heading")

        if not (re.fullmatch(r"[FDCR]", rec.type) or rec.type == ""):
            self.validate_or_warn(f"task '{base}' has malformed Type '{rec.type}'")
        if not (re.fullmatch(r"open|in_progress|done|cancelled", rec.status) or rec.status == ""):
            self.validate_or_warn(f"task '{base}' has malformed Status '{rec.status}'")
        if not (re.fullmatch(r"high|medium|low", rec.priority) or rec.priority == ""):
            self.validate_or_warn(f"task '{base}' has malformed Priority '{rec.priority}'")
        if not (re.match(DATETIME_PREFIX, rec.created) or rec.created == ""):
            self.validate_or_warn(f"task '{base}' has malformed Created '{rec.created}'")
        if not (re.match(DATETIME_PREFIX, rec.updated) or rec.updated == ""):
            self.validate_or_warn(f"task '{base}' has malformed Updated '{rec.updated}'")
        if not (rec.last_executed == "N/A" or re.match(DATETIME_PREFIX, rec.last_executed) or rec.last_executed == ""):
            self.validate_or_warn(f"task '{base}' has malformed Last executed '{rec.last_executed}'")
        if not (rec.target_date == "N/A" or re.match(DATE_FULL, rec.target_date) or rec.target_date == ""):
            self.validate_or_warn(f"task '{base}' has malformed Target date '{rec.target_date}'")
        if not (rec.deadline == "N/A" or re.match(DATE_FULL, rec.deadline) or rec.deadline == ""):
            self.validate_or_warn(f"task '{base}' has malformed Deadline '{rec.deadline}'")

        if not required_missing and rec.taskid != "" and rec.type != "":
            pattern = rf"^{re.escape(rec.taskid)}-{re.escape(rec.type)}_[a-z0-9]([a-z0-9-]*[a-z0-9])?\.md$"
            if not re.fullmatch(pattern, base):
                self.validate_or_warn(
                    f"task '{base}' filename does not match metadata Task ID '{rec.taskid}' and Type '{rec.type}'"
                )

    # ---- task size / execution log rotation -------------------------------

    @staticmethod
    def execution_log_line_count(text: str) -> int:
        """Count lines inside the `## Execution log` section body (heading excluded)."""
        in_section = False
        count = 0
        for line in text.splitlines():
            if re.fullmatch(r"##[ \t\r\f\v]+Execution log[ \t\r\f\v]*", line):
                in_section = True
                continue
            if in_section and re.match(r"^##[ \t\r\f\v]+", line):
                break
            if in_section:
                count += 1
        return count

    def check_task_size(self, path: Path, base: str, taskid: str) -> None:
        text = path.read_text(encoding="utf-8")
        total_lines = len(text.splitlines())
        if total_lines > 400:
            self.warn(f"task '{base}' exceeds 400 lines")

        log_lines = self.execution_log_line_count(text)
        if log_lines > 200:
            self.warn(
                f"task '{base}' execution log exceeds 200 lines (run: at ledger rotate-log {taskid})"
            )

    # ---- record a task ---------------------------------------------------

    def record_task(self, path: Path, dir_label: str) -> None:
        base = path.name
        rec = self.extract_task(path)
        self.validate_task_metadata(path, base, rec)

        if rec.taskid == "":
            return

        area = rec.area or "global"
        status = rec.status or "open"
        priority = rec.priority or "medium"
        updated = rec.updated or "N/A"
        taskid = rec.taskid

        self.check_task_size(path, base, taskid)

        self.task_count[taskid] = self.task_count.get(taskid, 0) + 1
        if self.task_count[taskid] == 1:
            self.task_ids.append(taskid)
        else:
            self.validate_or_warn(f"ambiguous task id '{taskid}' appears in multiple task files")

        self.task_file[taskid] = path
        self.task_base[taskid] = base
        self.task_dir[taskid] = dir_label
        self.task_type[taskid] = rec.type
        self.task_area[taskid] = area
        self.task_status[taskid] = status
        self.task_priority[taskid] = priority
        self.task_updated[taskid] = updated
        self.task_title[taskid] = rec.title
        self.task_phase[taskid] = f"{rec.done}/{rec.total}"

        prefix = taskid.rsplit("-", 1)[0]
        if prefix == taskid or not re.fullmatch(r"[A-Z][A-Z0-9]*-[0-9]{3,}", taskid):
            self.validate_or_warn(f"task '{base}' has malformed Task ID '{taskid}'")
        elif prefix in self.prefix_area:
            expected_area = self.prefix_area[prefix]
            if area != expected_area:
                self.validate_or_warn(
                    f"task '{taskid}' prefix '{prefix}' maps to area '{expected_area}' but metadata says '{area}'"
                )
        else:
            self.validate_or_warn(f"task '{taskid}' uses unregistered prefix '{prefix}'")

        if area not in self.area_prefix:
            self.validate_or_warn(f"task '{taskid}' uses unregistered area '{area}'")

        lifecycle = f"{dir_label}:{status}"
        if lifecycle in ("_todos:open", "_todos:in_progress", "_todos_archived:done", "_todos_archived:cancelled"):
            pass
        elif lifecycle in ("_todos:done", "_todos:cancelled"):
            self.validate_or_warn(
                f"terminal task '{taskid}' has Status '{status}' but is still in docs/tasks_manager/_todos/"
            )
        elif lifecycle in ("_todos_archived:open", "_todos_archived:in_progress"):
            self.validate_or_warn(
                f"active task '{taskid}' has Status '{status}' but is in docs/tasks_manager/_todos_archived/"
            )

        if dir_label == "_todos_archived":
            self.validate_completion_archive(path, taskid)

        if status == "open":
            self.area_open[area] = self.area_open.get(area, 0) + 1
        elif status == "in_progress":
            self.area_inprogress[area] = self.area_inprogress.get(area, 0) + 1
        elif status in ("done", "cancelled"):
            self.area_done[area] = self.area_done.get(area, 0) + 1

    # ---- inbox extraction / record --------------------------------------

    def extract_inbox(self, path: Path) -> tuple[str, str, str, str]:
        inboxid = captured = area = status = ""
        for key, val in mdtables.metadata_pairs(read_lines(path)):
            key = key.lower()
            if key == "inbox id":
                inboxid = val
            elif key == "captured":
                captured = val
            elif key == "area":
                area = val
            elif key == "status":
                status = val
        return inboxid, captured, area, status

    def record_inbox(self, path: Path, dir_label: str) -> None:
        base = path.name
        rel = self.rel_repo(path)
        inboxid, captured, area, status = self.extract_inbox(path)

        required_missing = False
        if inboxid == "":
            self.validate_or_warn(f"inbox '{base}' is missing Inbox ID")
            required_missing = True
        if captured == "":
            self.validate_or_warn(f"inbox '{base}' is missing Captured")
            required_missing = True
        if area == "":
            self.validate_or_warn(f"inbox '{base}' is missing Area")
            required_missing = True
        if status == "":
            self.validate_or_warn(f"inbox '{base}' is missing Status")
            required_missing = True

        if not (re.fullmatch(r"I-[0-9]{3,}", inboxid) or inboxid == ""):
            self.validate_or_warn(f"inbox '{base}' has malformed Inbox ID '{inboxid}'")
        if not (re.match(DATETIME_PREFIX, captured) or captured == ""):
            self.validate_or_warn(f"inbox '{base}' has malformed Captured '{captured}'")
        if not (re.fullmatch(r"new|promoted|dropped", status) or status == ""):
            self.validate_or_warn(f"inbox '{base}' has malformed Status '{status}'")

        if not required_missing and inboxid != "":
            pattern = rf"^{re.escape(inboxid)}_[a-z0-9]([a-z0-9-]*[a-z0-9])?\.md$"
            if not re.fullmatch(pattern, base):
                self.validate_or_warn(
                    f"inbox '{base}' filename does not match metadata Inbox ID '{inboxid}'"
                )

        if inboxid == "":
            return

        self.inbox_count[inboxid] = self.inbox_count.get(inboxid, 0) + 1
        if self.inbox_count[inboxid] == 1:
            self.inbox_ids.append(inboxid)
        else:
            self.validate_or_warn(f"ambiguous inbox id '{inboxid}' appears in multiple inbox files")

        self.inbox_dir[inboxid] = dir_label
        self.inbox_status[inboxid] = status or "new"

        lifecycle = f"{dir_label}:{status or 'new'}"
        if lifecycle in ("_inbox:new", "_inbox_archived:promoted", "_inbox_archived:dropped"):
            pass
        elif lifecycle in ("_inbox:promoted", "_inbox:dropped"):
            self.validate_or_warn(
                f"terminal inbox '{inboxid}' has Status '{status}' but is still in docs/tasks_manager/_inbox/"
            )
        elif lifecycle == "_inbox_archived:new":
            self.validate_or_warn(
                f"live inbox '{inboxid}' has Status 'new' but is in docs/tasks_manager/_inbox_archived/"
            )

        if area != "" and area not in self.area_prefix:
            self.validate_or_warn(f"inbox '{inboxid}' in {rel} uses unregistered area '{area}'")

    # ---- roadmap ---------------------------------------------------------

    def validate_roadmap_milestone(self, line: str, horizon: str) -> None:
        milestone_re = (
            r"^###[ \t\r\f\v]+Milestone:[ \t\r\f\v]+.+[ \t\r\f\v]"
            r"\((target|deadline):[ \t\r\f\v][0-9]{4}-[0-9]{2}-[0-9]{2}\)[ \t\r\f\v]*$"
        )
        expected = (
            "### Milestone: <name> (target: YYYY-MM-DD) or "
            "### Milestone: <name> (deadline: YYYY-MM-DD)"
        )
        if horizon == "" or horizon == "__invalid__":
            self.validate_or_warn(
                f"roadmap milestone heading appears outside an Urgent/Now/Next/Later/Someday horizon: '{line}'"
            )
        if not re.search(milestone_re, line):
            self.validate_or_warn(
                f"roadmap milestone heading has malformed syntax '{line}'; expected {expected}"
            )

    def parse_roadmap(self) -> None:
        if not self.roadmap.is_file():
            return
        horizon = ""
        in_fence = False
        for line in read_lines(self.roadmap):
            stripped = line.strip()
            if stripped.startswith("```") or stripped.startswith("~~~"):
                in_fence = not in_fence
                continue
            if in_fence:
                continue

            if line == "## Urgent" or line.startswith("## Urgent "):
                horizon = "Urgent"
                continue
            if line == "## Now" or line.startswith("## Now "):
                horizon = "Now"
                continue
            if line == "## Next" or line.startswith("## Next "):
                horizon = "Next"
                continue
            if line == "## Later" or line.startswith("## Later "):
                horizon = "Later"
                continue
            if line == "## Someday" or line.startswith("## Someday "):
                horizon = "Someday"
                continue
            if (
                line == "## Milestone"
                or line.startswith("## Milestone ")
                or line == "## Milestones"
                or line.startswith("## Milestones ")
            ):
                self.validate_or_warn(
                    "roadmap must not use a top-level ## Milestones section; "
                    "place milestone headings inside Urgent, Now, Next, Later, or Someday"
                )
                horizon = "__invalid__"
                continue
            if line.startswith("## "):
                horizon = "__invalid__"
                continue

            if re.match(r"^###[ \t\r\f\v]+Milestone", line):
                self.validate_roadmap_milestone(line, horizon)
                continue

            if horizon == "__invalid__":
                for ident in sorted(set(re.findall(r"(?:[A-Z][A-Z0-9]*|I)-[0-9]{3,}", line))):
                    self.validate_or_warn(
                        f"roadmap reference '{ident}' appears outside an Urgent/Now/Next/Later/Someday horizon"
                    )
                continue

            if horizon == "":
                continue

            for ident in sorted(set(re.findall(r"[A-Z][A-Z0-9]*-[0-9]{3,}", line))):
                if re.fullmatch(r"I-[0-9]{3,}", ident):
                    continue
                if ident not in self.roadmap_task_count:
                    self.roadmap_task_ids.append(ident)
                self.roadmap_task_count[ident] = self.roadmap_task_count.get(ident, 0) + 1
                self.roadmap_task_horizon.setdefault(ident, horizon)

            for ident in sorted(set(re.findall(r"I-[0-9]{3,}", line))):
                if ident not in self.roadmap_inbox_count:
                    self.roadmap_inbox_ids.append(ident)
                    self.roadmap_inbox_horizon[ident] = horizon
                self.roadmap_inbox_count[ident] = self.roadmap_inbox_count.get(ident, 0) + 1

    def assign_roadmap_horizons(self) -> None:
        for ident in self.roadmap_task_ids:
            if self.roadmap_task_count[ident] > 1:
                self.validate_or_warn(
                    f"ambiguous roadmap task reference '{ident}' appears {self.roadmap_task_count[ident]} times"
                )
                continue
            if ident not in self.task_count:
                self.validate_or_warn(f"missing roadmap task reference '{ident}'")
                continue
            if self.task_count[ident] > 1:
                self.validate_or_warn(f"ambiguous roadmap task reference '{ident}' matches multiple files")
                continue
            area = self.task_area[ident]
            horizon = self.roadmap_task_horizon[ident]
            if horizon == "Urgent":
                self.area_urgent[area] = self.area_urgent.get(area, 0) + 1
            elif horizon == "Now":
                self.area_now[area] = self.area_now.get(area, 0) + 1
            elif horizon == "Next":
                self.area_next[area] = self.area_next.get(area, 0) + 1
            elif horizon == "Later":
                self.area_later[area] = self.area_later.get(area, 0) + 1
            elif horizon == "Someday":
                self.area_someday[area] = self.area_someday.get(area, 0) + 1

        for ident in self.roadmap_inbox_ids:
            if self.roadmap_inbox_count[ident] > 1:
                self.validate_or_warn(
                    f"ambiguous roadmap inbox reference '{ident}' appears {self.roadmap_inbox_count[ident]} times"
                )
                continue
            if self.roadmap_inbox_horizon.get(ident, "") != "Someday":
                horizon = self.roadmap_inbox_horizon.get(ident) or "unknown"
                self.validate_or_warn(
                    f"roadmap inbox reference '{ident}' appears in {horizon} but inbox ideas may only "
                    "appear in Someday; promote with agents-tasks:triage-inbox before scheduling into Urgent, Now, Next, or Later"
                )
            if ident not in self.inbox_count:
                self.validate_or_warn(f"missing roadmap inbox reference '{ident}'")
                continue
            if self.inbox_count[ident] > 1:
                self.validate_or_warn(f"ambiguous roadmap inbox reference '{ident}' matches multiple files")
                continue
            if self.inbox_dir.get(ident) != "_inbox" or self.inbox_status.get(ident) != "new":
                self.validate_or_warn(
                    f"roadmap inbox reference '{ident}' is not a live new inbox idea; "
                    "remove it or reference its promoted task"
                )

    # ---- rendering helpers ----------------------------------------------

    def task_link_from_area(self, taskid: str) -> str:
        target = f"../tasks_manager/{self.task_dir[taskid]}/{self.task_base[taskid]}"
        return f"[{taskid}]({target})"

    def task_bullet(self, taskid: str) -> str:
        return "- {link} ({type}) {title} - {status}, {priority}, phase {phase}\n".format(
            link=self.task_link_from_area(taskid),
            type=self.task_type[taskid],
            title=md_escape(self.task_title[taskid]),
            status=self.task_status[taskid],
            priority=self.task_priority[taskid],
            phase=self.task_phase[taskid],
        )

    def section_for_area_horizon(self, area: str, horizon: str) -> str:
        out: list[str] = []
        for taskid in self.roadmap_task_ids:
            if self.roadmap_task_count[taskid] != 1:
                continue
            if self.task_count.get(taskid, 0) != 1:
                continue
            if self.task_area[taskid] != area:
                continue
            if self.roadmap_task_horizon[taskid] != horizon:
                continue
            if self.task_status[taskid] in ("done", "cancelled"):
                continue
            out.append(self.task_bullet(taskid))
        if not out:
            return "_No tasks._\n"
        return "".join(out)

    def section_for_area_unscheduled(self, area: str) -> str:
        out: list[str] = []
        for taskid in self.task_ids:
            if self.task_count[taskid] != 1:
                continue
            if self.task_area[taskid] != area:
                continue
            if self.task_status[taskid] not in ("open", "in_progress"):
                continue
            scheduled = self.roadmap_task_count.get(taskid, 0) == 1
            if scheduled:
                continue
            out.append(self.task_bullet(taskid))
        if not out:
            return "_No tasks._\n"
        return "".join(out)

    @staticmethod
    def replace_block(text: str, begin: str, end: str, block: str) -> str:
        lines = text.split("\n")
        if lines and lines[-1] == "":
            lines = lines[:-1]
        out: list[str] = []
        in_block = False
        seen = False
        for line in lines:
            if begin in line:
                out.append(begin + "\n")
                out.append(block)
                in_block = True
                seen = True
                continue
            if end in line:
                out.append(end + "\n")
                in_block = False
                continue
            if not in_block:
                out.append(line + "\n")
        if not seen:
            out.append("\n")
            out.append(begin + "\n")
            out.append(block)
            out.append(end + "\n")
        return "".join(out)

    # ---- ledgers ---------------------------------------------------------

    def render_active(self) -> str:
        rows: list[tuple[int, int, str, str]] = []
        for taskid in self.task_ids:
            if self.task_count[taskid] != 1:
                continue
            if self.task_dir[taskid] != "_todos":
                continue
            status = self.task_status[taskid]
            if status not in ("open", "in_progress"):
                continue
            skstatus = 0 if status == "in_progress" else 1
            priority = self.task_priority[taskid]
            skprio = {"high": 0, "medium": 1, "low": 2}.get(priority, 3)
            base = self.task_base[taskid]
            row = (
                f"| {taskid} | {self.task_type[taskid]} | {md_escape(self.task_title[taskid])} | "
                f"{self.task_area[taskid]} | {status} | {priority} | {self.task_phase[taskid]} | "
                f"{self.task_updated[taskid]} | [{base}](_todos/{base}) |"
            )
            rows.append((skstatus, skprio, taskid, row))

        rows.sort(key=lambda r: (r[0], r[1], r[2]))
        content = ACTIVE_HEADER + "\n"
        content += "".join(row + "\n" for _, _, _, row in rows)
        return content

    def render_done(self) -> str:
        rows: list[tuple[str, str, str]] = []
        for taskid in self.task_ids:
            if self.task_count[taskid] != 1:
                continue
            if self.task_dir[taskid] != "_todos_archived":
                continue
            status = self.task_status[taskid]
            if status not in ("done", "cancelled"):
                continue
            base = self.task_base[taskid]
            row = (
                f"| {taskid} | {self.task_type[taskid]} | {md_escape(self.task_title[taskid])} | "
                f"{self.task_area[taskid]} | {self.task_updated[taskid]} | - | "
                f"[{base}](_todos_archived/{base}) |"
            )
            rows.append((self.task_updated[taskid], taskid, row))

        rows.sort(key=lambda r: (r[0], r[1]), reverse=True)
        content = DONE_HEADER + "\n"
        content += "".join(row + "\n" for _, _, row in rows)
        return content

    def write_or_check(self, target: Path, content: str, label: str) -> None:
        if self.check_mode:
            if not target.is_file():
                self.error(f"{label} is missing at {self.rel_repo(target)}")
                return
            # Normalize the old note text before comparing so a ledger last
            # synced by the historical tooling isn't reported stale purely
            # because the generated-note wording changed.
            current = (target.read_text(encoding="utf-8")
                       .replace(OLD_GENERATED_NOTE, GENERATED_NOTE)
                       .replace(OLD_SYNC_REF, SYNC_REF))
            if current != content:
                self.error(f"{label} is stale at {self.rel_repo(target)}; run `at ledger sync`")
        else:
            target.write_text(content, encoding="utf-8")

    # ---- area pages ------------------------------------------------------

    def area_status_block(self, area: str) -> str:
        parts = [GENERATED_NOTE + "\n\n"]
        parts.append("## Urgent\n\n")
        parts.append(self.section_for_area_horizon(area, "Urgent"))
        parts.append("\n## Now\n\n")
        parts.append(self.section_for_area_horizon(area, "Now"))
        parts.append("\n## Next\n\n")
        parts.append(self.section_for_area_horizon(area, "Next"))
        parts.append("\n## Later\n\n")
        parts.append(self.section_for_area_horizon(area, "Later"))
        parts.append("\n## Someday\n\n")
        parts.append(self.section_for_area_horizon(area, "Someday"))
        parts.append("\n## Unscheduled\n\n")
        parts.append(self.section_for_area_unscheduled(area))
        return "".join(parts)

    def ensure_area_page(self, area: str, page_abs: Path) -> None:
        if page_abs.is_file():
            return
        page_abs.parent.mkdir(parents=True, exist_ok=True)
        title = area.replace("-", " ")
        content = (
            f"# {title}\n\n"
            f"{self.area_desc[area]}\n\n"
            f"Area context: [../resources/{area}/summary.md](../resources/{area}/summary.md).\n\n"
            f"{AREA_STATUS_BEGIN}\n"
            f"{GENERATED_NOTE}\n\n"
            "## Urgent\n\n_No tasks._\n\n"
            "## Now\n\n_No tasks._\n\n"
            "## Next\n\n_No tasks._\n\n"
            "## Later\n\n_No tasks._\n\n"
            "## Someday\n\n_No tasks._\n\n"
            "## Unscheduled\n\n_No tasks._\n"
            f"{AREA_STATUS_END}\n"
        )
        page_abs.write_text(content, encoding="utf-8")
        print(f"created area page: {self.rel_repo(page_abs)}")

    def process_area_pages(self) -> None:
        for area in self.areas:
            page_abs = self.page_abs_for(self.area_page[area])
            block = self.area_status_block(area)
            if self.check_mode:
                if not page_abs.is_file():
                    self.error(f"area page for '{area}' is missing at {self.rel_repo(page_abs)}")
                    continue
                current = page_abs.read_text(encoding="utf-8")
                expected = self.replace_block(current, AREA_STATUS_BEGIN, AREA_STATUS_END, block)
                self.write_or_check(page_abs, expected, f"generated area status block for '{area}'")
            else:
                self.ensure_area_page(area, page_abs)
                current = page_abs.read_text(encoding="utf-8")
                updated = self.replace_block(current, AREA_STATUS_BEGIN, AREA_STATUS_END, block)
                page_abs.write_text(updated, encoding="utf-8")

    def area_overview_block(self) -> str:
        parts = [GENERATED_NOTE + "\n\n"]
        parts.append(
            "| Area | Prefix | Description | Urgent | Now | Next | Later | Someday | Open | In Progress | Done | Page |\n"
        )
        parts.append(
            "|------|--------|-------------|--------|-----|------|-------|---------|------|-------------|------|------|\n"
        )
        for area in self.areas:
            page_abs = self.page_abs_for(self.area_page[area])
            rel = self.page_rel_from_areas(page_abs)
            parts.append(
                "| {area} | {prefix} | {desc} | {urgent} | {now} | {next} | {later} | {someday} | "
                "{open} | {inprogress} | {done} | [{base}]({rel}) |\n".format(
                    area=area,
                    prefix=self.area_prefix[area],
                    desc=md_escape(self.area_desc[area]),
                    urgent=self.area_urgent.get(area, 0),
                    now=self.area_now.get(area, 0),
                    next=self.area_next.get(area, 0),
                    later=self.area_later.get(area, 0),
                    someday=self.area_someday.get(area, 0),
                    open=self.area_open.get(area, 0),
                    inprogress=self.area_inprogress.get(area, 0),
                    done=self.area_done.get(area, 0),
                    base=os.path.basename(rel),
                    rel=rel,
                )
            )
        return "".join(parts)

    def process_overview(self) -> None:
        block = self.area_overview_block()
        if self.check_mode:
            if not self.areas_overview.is_file():
                self.error(f"area overview is missing at {self.rel_repo(self.areas_overview)}")
                return
            current = self.areas_overview.read_text(encoding="utf-8")
            expected = self.replace_block(current, AREA_OVERVIEW_BEGIN, AREA_OVERVIEW_END, block)
            self.write_or_check(self.areas_overview, expected, "generated area overview block")
        else:
            if not self.areas_overview.is_file():
                self.areas_overview.write_text("# Areas Overview\n", encoding="utf-8")
            current = self.areas_overview.read_text(encoding="utf-8")
            updated = self.replace_block(current, AREA_OVERVIEW_BEGIN, AREA_OVERVIEW_END, block)
            self.areas_overview.write_text(updated, encoding="utf-8")

    # ---- log rotation ------------------------------------------------------

    def find_task_path(self, taskid: str) -> Path | None:
        for directory in (self.todos, self.archived):
            if not directory.is_dir():
                continue
            matches = sorted(directory.glob(f"{taskid}-*.md"))
            if matches:
                return matches[0]
        return None

    def rotate_log(self, taskid: str) -> int:
        path = self.find_task_path(taskid)
        if path is None:
            print(f"ERROR: no task file found for '{taskid}'", file=sys.stderr)
            return 1

        lines = path.read_text(encoding="utf-8").split("\n")
        start: int | None = None
        end = len(lines)
        for index, line in enumerate(lines):
            if start is None and re.fullmatch(r"##[ \t\r\f\v]+Execution log[ \t\r\f\v]*", line):
                start = index
                continue
            if start is not None and index > start and re.match(r"^##[ \t\r\f\v]+", line):
                end = index
                break

        if start is None:
            print(f"ERROR: task '{taskid}' has no '## Execution log' section", file=sys.stderr)
            return 1

        body_text = "\n".join(lines[start + 1 : end]).strip("\n")
        pointer = f"See [_logs/{taskid}.md](../_logs/{taskid}.md). New entries go there."
        if body_text in ("", pointer):
            # Either genuinely empty, or already rotated and untouched since
            # (the section body is only the pointer we left last time) --
            # nothing new to move, and re-rotating would just duplicate the
            # pointer text into the log file.
            print(f"'{taskid}' execution log has nothing new to rotate")
            return 0

        logs_dir = self.tm / "_logs"
        logs_dir.mkdir(parents=True, exist_ok=True)
        log_path = logs_dir / f"{taskid}.md"
        header = f"# Execution log — {taskid}"
        if log_path.is_file():
            existing = log_path.read_text(encoding="utf-8").rstrip("\n")
            new_log_text = existing + "\n\n" + body_text + "\n"
        else:
            new_log_text = header + "\n\n" + body_text + "\n"
        log_path.write_text(new_log_text, encoding="utf-8")

        new_lines = lines[: start + 1] + ["", pointer, ""] + lines[end:]
        path.write_text("\n".join(new_lines), encoding="utf-8")

        print(f"rotated execution log for '{taskid}' to {self.rel_repo(log_path)}")
        return 0

    # ---- driver ----------------------------------------------------------

    def run(self) -> int:
        if self.check_mode:
            self.ensure_check_structure()
        else:
            for directory in (self.todos, self.archived, self.inbox, self.inbox_archived, self.areas_dir):
                directory.mkdir(parents=True, exist_ok=True)

        self.read_areas()

        for path in sorted(self.todos.glob("*.md")) if self.todos.is_dir() else []:
            self.record_task(path, "_todos")
        for path in sorted(self.archived.glob("*.md")) if self.archived.is_dir() else []:
            self.record_task(path, "_todos_archived")
        for path in sorted(self.inbox.glob("*.md")) if self.inbox.is_dir() else []:
            self.record_inbox(path, "_inbox")
        for path in sorted(self.inbox_archived.glob("*.md")) if self.inbox_archived.is_dir() else []:
            self.record_inbox(path, "_inbox_archived")

        self.write_or_check(self.active_ledger, self.render_active(), "active ledger")
        self.write_or_check(self.done_ledger, self.render_done(), "done ledger")

        self.parse_roadmap()
        self.assign_roadmap_horizons()

        self.process_area_pages()
        self.process_overview()

        if self.check_mode:
            if self.check_errors > 0:
                print(f"Task ledger validation failed: {self.check_errors} issue(s).", file=sys.stderr)
                return 1
            print("OK task ledgers valid")
            return 0

        print(
            "Ledgers synced: {active}, {done}, {overview}".format(
                active=self.rel_repo(self.active_ledger),
                done=self.rel_repo(self.done_ledger),
                overview=self.rel_repo(self.areas_overview),
            )
        )
        return 0


class _UsageError(Exception):
    pass


def _parse_args(argv: list[str]) -> tuple[bool, str | None, str | None]:
    """Parse [--check] [--root DIR] [rotate-log TASK_ID] in any order.

    Returns (check_mode, root_override, rotate_taskid). Raises _UsageError on a
    malformed invocation, or prints USAGE and returns via SystemExit(0) on --help.
    """
    check_mode = False
    root_override: str | None = None
    rotate_taskid: str | None = None

    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--check":
            check_mode = True
        elif arg == "--help":
            print(USAGE, end="")
            raise SystemExit(0)
        elif arg == "--root":
            i += 1
            if i >= len(argv):
                raise _UsageError("--root requires a directory argument")
            root_override = argv[i]
        elif arg == "rotate-log":
            i += 1
            if i >= len(argv):
                raise _UsageError("rotate-log requires a TASK_ID argument")
            rotate_taskid = argv[i]
        else:
            raise _UsageError(f"unknown option: {arg}")
        i += 1

    return check_mode, root_override, rotate_taskid


def _resolve_root(root_override: str | None) -> Path:
    if root_override:
        return Path(root_override).expanduser().resolve()
    try:
        result = subprocess.run(
            ["git", "-C", ".", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return Path.cwd()
    if result.returncode == 0:
        top = result.stdout.strip()
        if top:
            return Path(top).resolve()
    return Path.cwd()


def main(argv: list[str]) -> int:
    try:
        check_mode, root_override, rotate_taskid = _parse_args(argv)
    except _UsageError as exc:
        print(f"error: {exc}", file=sys.stderr)
        print(USAGE, end="", file=sys.stderr)
        return 2

    repo_root = _resolve_root(root_override)

    tm = repo_root / "docs" / "tasks_manager"
    if not tm.is_dir():
        action = "check" if check_mode else "sync"
        print(
            f"No docs/tasks_manager/ directory at {tm} - nothing to {action}. Run at init --with-tasks first.",
            file=sys.stderr,
        )
        return 0

    generator = Generator(repo_root, check_mode)
    if rotate_taskid is not None:
        return generator.rotate_log(rotate_taskid)
    return generator.run()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
