#!/usr/bin/env bash
# Hermetic smoke test against an installed Codex CLI. No model call or login is required.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
CODEX_BIN="${AT_CODEX_BIN:-codex}"
REQUIRED="${AT_REQUIRE_CODEX_LIVE:-0}"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

if ! command -v "$CODEX_BIN" >/dev/null 2>&1; then
  if [[ "$REQUIRED" == "1" ]]; then
    fail "AT_REQUIRE_CODEX_LIVE=1 but '$CODEX_BIN' is not on PATH"
  fi
  echo "SKIP: test-codex-live ($CODEX_BIN is not installed)"
  exit 0
fi

ACTUAL_VERSION="$("$CODEX_BIN" --version | awk '{print $NF}')"
EXPECTED_VERSION="${AT_EXPECT_CODEX_VERSION:-}"
python3 - "$ACTUAL_VERSION" "$EXPECTED_VERSION" <<'PYVERSION' || exit 1
import re
import sys

actual, expected = sys.argv[1:]


def version(value):
    match = re.match(r"^(\d+)\.(\d+)\.(\d+)", value)
    if not match:
        raise SystemExit(f"FAIL: cannot parse Codex version: {value!r}")
    return tuple(map(int, match.groups()))


if version(actual) < version("0.147.0"):
    raise SystemExit(f"FAIL: Codex {actual} is older than supported minimum 0.147.0")
if expected and version(actual) != version(expected):
    raise SystemExit(f"FAIL: expected Codex {expected}, found {actual}")
PYVERSION

WORKDIR="$(mktemp -d "$ROOT/.codex-live.XXXXXX")"
trap 'rm -rf "${WORKDIR}"' EXIT
TEST_HOME="$WORKDIR/home"
PROJECT="$WORKDIR/project"
mkdir -p "$TEST_HOME" "$PROJECT"

VERSION="$(python3 -c 'import json; print(json.load(open("plugins/agents-core/.claude-plugin/plugin.json"))["version"])')"

HOME="$TEST_HOME" "$CODEX_BIN" plugin marketplace add "$ROOT" --json >/dev/null
for plugin in agents-core agents-extras agents-personal agents-tasks; do
  HOME="$TEST_HOME" "$CODEX_BIN" plugin add "$plugin@agents-template" --json >/dev/null
done

INVENTORY="$(HOME="$TEST_HOME" "$CODEX_BIN" plugin list --json)"
for plugin in agents-core agents-extras agents-personal agents-tasks; do
  jq -e --arg plugin "$plugin" --arg version "$VERSION" '
    any(.installed[];
      .name == $plugin and .marketplaceName == "agents-template" and
      .version == $version and .installed == true and .enabled == true)
  ' <<<"$INVENTORY" >/dev/null || fail "$plugin is not installed and enabled at $VERSION"
done

CACHE_BASE="$TEST_HOME/.codex/plugins/cache/agents-template"
CORE_CACHE="$CACHE_BASE/agents-core/$VERSION"
TASKS_CACHE="$CACHE_BASE/agents-tasks/$VERSION"
[[ -x "$CORE_CACHE/bin/at" ]] || fail "installed agents-core is missing executable bin/at"
[[ -f "$CORE_CACHE/hooks/hooks.codex.json" ]] || fail "installed Codex hook manifest is missing"
[[ -d "$CORE_CACHE/codex/agents" ]] || fail "installed Codex agent roles are missing"
[[ -x "$TASKS_CACHE/skills/task-ledger/scripts/reserve_work_item.sh" ]] || \
  fail "installed task reservation helper is missing or not executable"

SKILL_COUNT="$(find "$CACHE_BASE" -path '*/skills/*/SKILL.md' -type f | wc -l | tr -d ' ')"
[[ "$SKILL_COUNT" == "71" ]] || fail "installed payload exposes $SKILL_COUNT skills, expected 71"
POLICY_COUNT="$(find "$CACHE_BASE" -path '*/skills/*/agents/openai.yaml' -type f | wc -l | tr -d ' ')"
[[ "$POLICY_COUNT" == "10" ]] || fail "installed payload exposes $POLICY_COUNT Codex policies, expected 10"
while IFS= read -r policy; do
  grep -q '^# GENERATED by scripts/build.py' "$policy" || fail "$policy is not generator-owned"
  grep -q '^  products: \[CODEX\]$' "$policy" || fail "$policy does not target Codex"
  grep -q '^  allow_implicit_invocation: false$' "$policy" || \
    fail "$policy allows implicit invocation"
done < <(find "$CACHE_BASE" -path '*/skills/*/agents/openai.yaml' -type f | sort)

ROLE_COUNT="$(find "$CORE_CACHE/codex/agents" -maxdepth 1 -name '*.toml' -type f | wc -l | tr -d ' ')"
[[ "$ROLE_COUNT" == "6" ]] || fail "installed payload exposes $ROLE_COUNT Codex roles, expected 6"
for role in "$CORE_CACHE"/codex/agents/*.toml; do
  grep -q '^name = "' "$role" || fail "$role has no role name"
  grep -q '^description = "' "$role" || fail "$role has no role description"
  grep -q '^developer_instructions = """' "$role" || fail "$role has no instructions"
done

jq -e '
  (.hooks.PreToolUse | length) == 2 and
  (.hooks.PostToolUse | length) == 1 and
  (.hooks.SubagentStop | length) == 1 and
  ([.hooks[][]?.hooks[]?.command] | length) == 6
' "$CORE_CACHE/hooks/hooks.codex.json" >/dev/null || fail "installed Codex hook manifest is malformed"

SAFE_PAYLOAD="$(jq -nc --arg command 'git status --short' '{tool_input: {command: $command}}')"
printf '%s\n' "$SAFE_PAYLOAD" | "$CORE_CACHE/hooks/block-dangerous-git.sh" >/dev/null || \
  fail "git safety hook rejected a read-only command"
DANGEROUS_PAYLOAD="$(jq -nc --arg command 'git push --force' '{tool_input: {command: $command}}')"
set +e
HOOK_OUTPUT="$(printf '%s\n' "$DANGEROUS_PAYLOAD" | "$CORE_CACHE/hooks/block-dangerous-git.sh" 2>&1)"
HOOK_RC=$?
set -e
[[ "$HOOK_RC" == "2" ]] || fail "git safety hook did not block a forced push: $HOOK_OUTPUT"

# Exercise the installed CLI's real local-marketplace update/reinstall path before using its cache.
HOME="$TEST_HOME" "$CORE_CACHE/bin/at" update --codex >/dev/null || \
  fail "at update --codex failed for the local marketplace"

git -C "$PROJECT" init -q
printf '# Codex live smoke\n' > "$PROJECT/README.md"
export PATH="$CORE_CACHE/bin:$PATH"
(
  cd "$PROJECT"
  HOME="$TEST_HOME" at init --all >/dev/null
  [[ "$(find .codex/agents -maxdepth 1 -name '*.toml' -type f | wc -l | tr -d ' ')" == "6" ]] || \
    fail "at init did not seed all six Codex roles"
  [[ "$(HOME="$TEST_HOME" at seed-path)" == "$CORE_CACHE/seed/AGENTS.md" ]] || \
    fail "at seed-path did not resolve the installed Codex cache"
  HOME="$TEST_HOME" at doctor --codex >/dev/null || fail "at doctor --codex failed"

  INBOX_PATH="$(HOME="$TEST_HOME" at reserve inbox codex-live-capture)"
  printf '%s\n' \
    '| Field    | Value                |' \
    '|----------|----------------------|' \
    '| Inbox ID | I-001                |' \
    '| Captured | 2026-09-02T00:00:00Z |' \
    '| Area     | global               |' \
    '| Status   | new                  |' \
    '' \
    '## Codex live capture' \
    '' \
    'Verify that the installed task workflow records an inbox idea.' > "$INBOX_PATH"
  HOME="$TEST_HOME" at ledger check >/dev/null || fail "recorded inbox idea failed ledger validation"
  HOME="$TEST_HOME" at repos-check >/dev/null || fail "seeded repo registry failed validation"
)

echo "test-codex-live: ok (Codex $ACTUAL_VERSION, 71 skills, 10 policies, 6 roles)"
