#!/usr/bin/env python3
"""Static dual-harness contract checks that require no Claude or Codex CLI."""

from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BUILD_PATH = ROOT / "scripts" / "build.py"

spec = importlib.util.spec_from_file_location("agents_template_build", BUILD_PATH)
assert spec and spec.loader
build = importlib.util.module_from_spec(spec)
spec.loader.exec_module(build)


class SkillContractTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.skills = sorted((ROOT / "plugins").glob("*/skills/*/SKILL.md"))
        cls.metadata = {path: build.skill_frontmatter(path) for path in cls.skills}

    def test_repository_has_expected_skill_inventory(self) -> None:
        self.assertEqual(len(self.skills), 71)
        names = [str(metadata["name"]) for metadata in self.metadata.values()]
        self.assertEqual(len(names), len(set(names)), "Codex $skill names must be globally unique")

    def test_skill_shape_matches_repository_contract(self) -> None:
        for path, metadata in self.metadata.items():
            with self.subTest(skill=path):
                name = str(metadata["name"])
                description = str(metadata["description"])
                self.assertEqual(name, path.parent.name)
                self.assertLessEqual(len(description), 1024)
                self.assertLessEqual(len(path.read_text().splitlines()), 500)
                plugin = path.parents[2].name
                self.assertLessEqual(len(f"{plugin}:{name}"), 64)

    def test_exactly_ten_skills_are_explicit_only(self) -> None:
        disabled = {
            f"{path.parents[2].name}:{metadata['name']}"
            for path, metadata in self.metadata.items()
            if metadata["disable_model_invocation"]
        }
        self.assertEqual(disabled, {
            "agents-core:grill-me",
            "agents-core:setup-project",
            "agents-core:squash-workspace-commits",
            "agents-core:wait-what",
            "agents-extras:grill-with-docs",
            "agents-extras:to-questionnaire",
            "agents-personal:google-docs-refine",
            "agents-tasks:complete-task",
            "agents-tasks:tidy-repo",
            "agents-tasks:wayfinder",
        })

    def test_generated_codex_policy_matches_claude_flag(self) -> None:
        targets = build.targets(build.load_plugins())
        policies = {
            path: content for path, content in targets.items()
            if path.name == "openai.yaml" and path.parent.name == "agents"
        }
        self.assertEqual(len(policies), 10)
        for skill_path, metadata in self.metadata.items():
            policy_path = skill_path.parent / "agents" / "openai.yaml"
            with self.subTest(skill=skill_path):
                self.assertEqual(policy_path in policies, metadata["disable_model_invocation"])
                if policy_path in policies:
                    content = policies[policy_path]
                    self.assertIn("products: [CODEX]", content)
                    self.assertIn("allow_implicit_invocation: false", content)
                    self.assertTrue(content.startswith("# GENERATED by scripts/build.py"))
                    self.assertEqual(policy_path.read_text(), content)

    def test_generated_policy_ownership_is_detectable(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            owned = root / "owned.yaml"
            foreign = root / "foreign.yaml"
            owned.write_text("# GENERATED by scripts/build.py from source; do not edit by hand.\n")
            foreign.write_text("policy:\n  allow_implicit_invocation: false\n")
            self.assertTrue(build.is_generated_skill_policy(owned))
            self.assertFalse(build.is_generated_skill_policy(foreign))
            orphaned, conflicts = build.classify_skill_policy_files(set(), {owned, foreign})
            self.assertEqual(orphaned, [owned])
            self.assertEqual(conflicts, [foreign])

    def test_expected_generated_policy_is_not_an_orphan(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            policy = Path(temp) / "openai.yaml"
            policy.write_text("# GENERATED by scripts/build.py from source; do not edit by hand.\n")
            orphaned, conflicts = build.classify_skill_policy_files({policy}, {policy})
            self.assertEqual(orphaned, [])
            self.assertEqual(conflicts, [])


if __name__ == "__main__":
    unittest.main()
