#!/usr/bin/env python3
"""Generate every mirrored/derived file in this repo from its Claude-side source.

Sources of truth:  plugins/*/.claude-plugin/plugin.json, plugins/*/hooks/hooks.json,
                   plugins/*/agents/*.md, plugins/*/skills/*/SKILL.md invocation flags
Generated:         .claude-plugin/marketplace.json, .agents/plugins/marketplace.json,
                   plugins/*/.codex-plugin/plugin.json, plugins/*/hooks/hooks.codex.json,
                   plugins/*/codex/agents/*.toml,
                   plugins/*/skills/*/agents/openai.yaml for explicit-only skills
Usage: python3 scripts/build.py [--check]
"""
from __future__ import annotations
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = ROOT / "plugins"
MARKETPLACE_NAME = "agents-template"
OWNER = {"name": "Vitalii Toderian", "url": "https://github.com/toderian"}
GENERATED_BANNER = "GENERATED by scripts/build.py from {src}; do not edit by hand."
SKILL_POLICY_NAME = "openai.yaml"

def load_plugins() -> list[dict]:
    out = []
    for manifest in sorted(PLUGINS_DIR.glob("*/.claude-plugin/plugin.json")):
        data = json.loads(manifest.read_text())
        data["_dir"] = manifest.parent.parent
        assert data["name"] == data["_dir"].name, f"{manifest}: name != dir"
        out.append(data)
    return out

def render_marketplace_claude(plugins: list[dict]) -> str:
    return json.dumps({
        "name": MARKETPLACE_NAME,
        "description": "Agents template: operating contract, skills, hooks and subagents for Claude Code and Codex.",
        "owner": OWNER,
        "plugins": [{
            "name": p["name"], "description": p["description"], "version": p["version"],
            "source": f"./plugins/{p['name']}",
        } for p in plugins],
    }, indent=2) + "\n"

def render_marketplace_codex(plugins: list[dict]) -> str:
    return json.dumps({
        "name": MARKETPLACE_NAME,
        "interface": {"displayName": "Agents Template"},
        "plugins": [{
            "name": p["name"], "description": p["description"], "version": p["version"],
            "source": {"source": "local", "path": f"./plugins/{p['name']}"},
            "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
            "category": "Developer Tools",
        } for p in plugins],
    }, indent=2) + "\n"

def render_codex_plugin(p: dict) -> str:
    out = {
        "name": p["name"], "version": p["version"], "description": p["description"],
        "author": p.get("author", OWNER), "repository": p.get("repository"),
        "license": p.get("license"), "keywords": p.get("keywords", []),
        "skills": "./skills/",
        "interface": {"displayName": p["name"], "shortDescription": p["description"][:120],
                      "category": "Developer Tools"},
    }
    if (p["_dir"] / "hooks" / "hooks.json").exists():
        out["hooks"] = "./hooks/hooks.codex.json"
    return json.dumps({k: v for k, v in out.items() if v is not None}, indent=2) + "\n"

def render_codex_hooks(claude_hooks: dict) -> dict:
    text = json.dumps(claude_hooks)
    text = text.replace("${CLAUDE_PLUGIN_ROOT}", "${PLUGIN_ROOT}").replace("MultiEdit|", "")
    return json.loads(text)

def render_codex_agent(md_path: Path) -> str:
    text = md_path.read_text()
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    fm, body = m.group(1), m.group(2).strip()
    name = re.search(r"^name:\s*(.+)$", fm, re.M).group(1).strip()
    desc = re.search(r"^description:\s*(.+)$", fm, re.M).group(1).strip().strip('"')
    desc = desc.replace("\\", "\\\\").replace('"', '\\"')
    body = re.sub(
        r"\$\{CLAUDE_PLUGIN_ROOT\}/skills/([\w-]+)/SKILL\.md",
        r"the `agents-core:\1` skill ($agents-core:\1)",
        body,
    )
    body = re.sub(
        r"\$\{CLAUDE_PLUGIN_ROOT\}/skills/([\w-]+)/references/([\w./-]+)",
        r"the `agents-core:\1` skill's references/\2",
        body,
    )
    body = body.replace('"""', "'''")
    return (f'# {GENERATED_BANNER.format(src=md_path.relative_to(ROOT))}\n'
            f'name = "{name}"\ndescription = "{desc}"\n'
            f'developer_instructions = """\n{body}\n"""\n')

def skill_frontmatter(skill_path: Path) -> dict[str, str | bool]:
    """Read the small frontmatter subset needed by the build without a YAML dependency."""
    text = skill_path.read_text()
    match = re.match(r"---\n(.*?)\n---(?:\n|$)", text, re.S)
    if match is None:
        raise ValueError(f"{skill_path}: missing YAML frontmatter")
    frontmatter = match.group(1)

    def scalar(key: str) -> str:
        found = re.search(rf"^{re.escape(key)}:\s*(.+)$", frontmatter, re.M)
        if found is None:
            raise ValueError(f"{skill_path}: missing {key}")
        raw = found.group(1).strip()
        if raw.startswith(('"', "'")):
            try:
                return json.loads(raw) if raw.startswith('"') else raw[1:-1]
            except json.JSONDecodeError as exc:
                raise ValueError(f"{skill_path}: invalid quoted {key}: {exc}") from exc
        return raw

    disabled = re.search(
        r"^disable-model-invocation:\s*(true|false)\s*$", frontmatter, re.M,
    )
    return {
        "name": scalar("name"),
        "description": scalar("description"),
        "disable_model_invocation": disabled is not None and disabled.group(1) == "true",
    }

def render_codex_skill_policy(skill_path: Path, metadata: dict[str, str | bool]) -> str:
    name = str(metadata["name"])
    description = re.sub(r"\s+", " ", str(metadata["description"])).strip()
    short = re.split(r"(?<=[.!?])\s+", description, maxsplit=1)[0]
    if len(short) > 240:
        short = short[:237].rsplit(" ", 1)[0].rstrip(" ,;:") + "..."
    display_name = " ".join(part.capitalize() for part in name.split("-"))
    return (
        f"# {GENERATED_BANNER.format(src=skill_path.relative_to(ROOT))}\n"
        "interface:\n"
        f"  display_name: {json.dumps(display_name, ensure_ascii=False)}\n"
        f"  short_description: {json.dumps(short, ensure_ascii=False)}\n"
        "policy:\n"
        "  products: [CODEX]\n"
        "  allow_implicit_invocation: false\n"
    )

def skill_policy_paths(plugins_dir: Path = PLUGINS_DIR) -> list[Path]:
    return sorted(plugins_dir.glob(f"*/skills/*/agents/{SKILL_POLICY_NAME}"))

def is_generated_skill_policy(path: Path) -> bool:
    try:
        first_line = path.read_text().splitlines()[0]
    except (OSError, IndexError):
        return False
    return first_line.startswith("# GENERATED by scripts/build.py from ")

def classify_skill_policy_files(
    expected: set[Path], existing: set[Path],
) -> tuple[list[Path], list[Path]]:
    """Return (banner-owned orphans, unowned conflicts) in stable order."""
    conflicts = sorted(path for path in existing if not is_generated_skill_policy(path))
    orphaned = sorted(path for path in existing - expected if path not in conflicts)
    return orphaned, conflicts

def targets(plugins: list[dict]) -> dict[Path, str]:
    t = {
        ROOT / ".claude-plugin/marketplace.json": render_marketplace_claude(plugins),
        ROOT / ".agents/plugins/marketplace.json": render_marketplace_codex(plugins),
    }
    for p in plugins:
        t[p["_dir"] / ".codex-plugin/plugin.json"] = render_codex_plugin(p)
        hooks = p["_dir"] / "hooks/hooks.json"
        if hooks.exists():
            t[p["_dir"] / "hooks/hooks.codex.json"] = json.dumps(
                render_codex_hooks(json.loads(hooks.read_text())), indent=2) + "\n"
        for md in sorted((p["_dir"] / "agents").glob("*.md")) if (p["_dir"] / "agents").is_dir() else []:
            t[p["_dir"] / "codex/agents" / (md.stem + ".toml")] = render_codex_agent(md)
        for skill in sorted((p["_dir"] / "skills").glob("*/SKILL.md")):
            metadata = skill_frontmatter(skill)
            if metadata["disable_model_invocation"]:
                target = skill.parent / "agents" / SKILL_POLICY_NAME
                t[target] = render_codex_skill_policy(skill, metadata)
    return t

def main(argv: list[str]) -> int:
    check = "--check" in argv
    plugins = load_plugins()
    generated = targets(plugins)
    expected_skill_policies = {
        path for path in generated if path.name == SKILL_POLICY_NAME and path.parent.name == "agents"
    }
    existing_skill_policies = set(skill_policy_paths())
    orphaned, conflicts = classify_skill_policy_files(
        expected_skill_policies, existing_skill_policies,
    )
    if conflicts:
        for path in conflicts:
            print(f"CONFLICT {path.relative_to(ROOT)} is not build-owned", file=sys.stderr)
        return 1
    stale = []
    for path, content in generated.items():
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
                print(f"wrote {path.relative_to(ROOT)}")
    for path in orphaned:
        stale.append(path)
        if not check:
            path.unlink()
            try:
                path.parent.rmdir()
            except OSError:
                pass
            print(f"removed {path.relative_to(ROOT)}")
    if check and stale:
        for p in stale:
            print(f"STALE {p.relative_to(ROOT)}", file=sys.stderr)
        return 1
    print("build: ok" if not stale else f"build: wrote {len(stale)} file(s)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
