#!/usr/bin/env python3
"""Generate every mirrored/derived file in this repo from its Claude-side source.

Sources of truth:  plugins/*/.claude-plugin/plugin.json, plugins/*/hooks/hooks.json,
                   plugins/*/agents/*.md
Generated:         .claude-plugin/marketplace.json, .agents/plugins/marketplace.json,
                   plugins/*/.codex-plugin/plugin.json, plugins/*/hooks/hooks.codex.json,
                   plugins/*/codex/agents/*.toml
Usage: python3 scripts/build.py [--check]
"""
from __future__ import annotations
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = ROOT / "plugins"
MARKETPLACE_NAME = "agents-template"
OWNER = {"name": "Vitalii Toderian", "url": "https://github.com/toderian"}
GENERATED_BANNER = "GENERATED by scripts/build.py from {src}; do not edit by hand."

def load_plugins() -> list[dict]:
    out = []
    for manifest in sorted(PLUGINS_DIR.glob("*/.claude-plugin/plugin.json")):
        data = json.loads(manifest.read_text())
        data["_dir"] = manifest.parent.parent
        assert data["name"] == data["_dir"].name, f"{manifest}: name != dir"
        out.append(data)
    return out

def render_marketplace_claude(plugins: list[dict]) -> str:
    return json.dumps({
        "name": MARKETPLACE_NAME,
        "description": "Agents template: operating contract, skills, hooks and subagents for Claude Code and Codex.",
        "owner": OWNER,
        "plugins": [{
            "name": p["name"], "description": p["description"], "version": p["version"],
            "source": f"./plugins/{p['name']}",
        } for p in plugins],
    }, indent=2) + "\n"

def render_marketplace_codex(plugins: list[dict]) -> str:
    return json.dumps({
        "name": MARKETPLACE_NAME,
        "interface": {"displayName": "Agents Template"},
        "plugins": [{
            "name": p["name"], "description": p["description"], "version": p["version"],
            "source": {"source": "local", "path": f"./plugins/{p['name']}"},
            "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
            "category": "Developer Tools",
        } for p in plugins],
    }, indent=2) + "\n"

def render_codex_plugin(p: dict) -> str:
    out = {
        "name": p["name"], "version": p["version"], "description": p["description"],
        "author": p.get("author", OWNER), "repository": p.get("repository"),
        "license": p.get("license"), "keywords": p.get("keywords", []),
        "skills": "./skills/",
        "interface": {"displayName": p["name"], "shortDescription": p["description"][:120],
                      "category": "Developer Tools"},
    }
    if (p["_dir"] / "hooks" / "hooks.json").exists():
        out["hooks"] = "./hooks/hooks.codex.json"
    return json.dumps({k: v for k, v in out.items() if v is not None}, indent=2) + "\n"

def render_codex_hooks(claude_hooks: dict) -> dict:
    text = json.dumps(claude_hooks)
    text = text.replace("${CLAUDE_PLUGIN_ROOT}", "${PLUGIN_ROOT}").replace("MultiEdit|", "")
    return json.loads(text)

def render_codex_agent(md_path: Path) -> str:              # filled in Task 4
    raise NotImplementedError

def targets(plugins: list[dict]) -> dict[Path, str]:
    t = {
        ROOT / ".claude-plugin/marketplace.json": render_marketplace_claude(plugins),
        ROOT / ".agents/plugins/marketplace.json": render_marketplace_codex(plugins),
    }
    for p in plugins:
        t[p["_dir"] / ".codex-plugin/plugin.json"] = render_codex_plugin(p)
        hooks = p["_dir"] / "hooks/hooks.json"
        if hooks.exists():
            t[p["_dir"] / "hooks/hooks.codex.json"] = json.dumps(
                render_codex_hooks(json.loads(hooks.read_text())), indent=2) + "\n"
        for md in sorted((p["_dir"] / "agents").glob("*.md")) if (p["_dir"] / "agents").is_dir() else []:
            t[p["_dir"] / "codex/agents" / (md.stem + ".toml")] = render_codex_agent(md)
    return t

def main(argv: list[str]) -> int:
    check = "--check" in argv
    plugins = load_plugins()
    stale = []
    for path, content in targets(plugins).items():
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
                print(f"wrote {path.relative_to(ROOT)}")
    if check and stale:
        for p in stale: print(f"STALE {p.relative_to(ROOT)}", file=sys.stderr)
        return 1
    print("build: ok" if not stale else f"build: wrote {len(stale)} file(s)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
