#!/usr/bin/env bash
#
# Regenerate the "Available skills" table in _base/README.md from
# playbooks/skills/*.md. Run after adding, renaming, or removing a skill.
#
# The script preserves everything outside the markers:
#
#   <!-- BEGIN skills-table -->
#   ...generated content...
#   <!-- END skills-table -->
#
# For each skill, the row description comes from:
#   1. the matching Claude wrapper's frontmatter `description:` (preferred — it's
#      the same one-line summary users see when invoking the skill), or
#   2. the first non-heading paragraph under `## Purpose` in the playbook, or
#   3. "(no description)" as a last resort.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
README="$REPO_ROOT/_base/README.md"
PLAYBOOKS_DIR="$REPO_ROOT/playbooks/skills"
CLAUDE_SKILLS_DIR="$REPO_ROOT/.claude/skills"

BEGIN_MARKER='<!-- BEGIN skills-table -->'
END_MARKER='<!-- END skills-table -->'

if [[ ! -f "$README" ]]; then
  echo "error: $README not found" >&2
  exit 1
fi

if ! grep -qF "$BEGIN_MARKER" "$README" || ! grep -qF "$END_MARKER" "$README"; then
  echo "error: $README is missing the BEGIN/END skills-table markers" >&2
  exit 1
fi

# Extract one-line description for a skill. Trims whitespace and collapses to a single line.
description_for() {
  local name="$1"
  local wrapper="$CLAUDE_SKILLS_DIR/$name/SKILL.md"
  local playbook="$PLAYBOOKS_DIR/$name.md"

  if [[ -f "$wrapper" ]]; then
    local desc
    desc=$(awk '
      /^---[[:space:]]*$/ { if (in_fm) { exit } else { in_fm = 1; next } }
      in_fm && /^description:[[:space:]]*/ {
        sub(/^description:[[:space:]]*/, "")
        # Strip surrounding quotes if present
        sub(/^"/, ""); sub(/"$/, "")
        sub(/^'\''/, ""); sub(/'\''$/, "")
        print
        exit
      }
    ' "$wrapper")
    if [[ -n "$desc" ]]; then
      printf '%s' "$desc"
      return
    fi
  fi

  if [[ -f "$playbook" ]]; then
    local purpose
    purpose=$(awk '
      /^## Purpose/ { in_section = 1; next }
      in_section && /^## / { exit }
      in_section && NF { print; exit }
    ' "$playbook")
    if [[ -n "$purpose" ]]; then
      printf '%s' "$purpose"
      return
    fi
  fi

  printf '(no description)'
}

# Build the new table body.
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "$BEGIN_MARKER"
  echo "<!-- This block is auto-generated by scripts/gen-skills-table.sh from playbooks/skills/*.md — do not edit by hand. -->"
  echo
  echo "| Skill | Description |"
  echo "|-------|-------------|"
  # Skills can be either playbooks/skills/<name>.md or playbooks/skills/<name>/ (directory form).
  while IFS= read -r name; do
    desc=$(description_for "$name")
    # Escape pipes in the description so they don't break the table.
    desc=${desc//|/\\|}
    printf '| %s | %s |\n' "$name" "$desc"
  done < <(
    {
      find "$PLAYBOOKS_DIR" -maxdepth 1 -mindepth 1 -name '*.md' -printf '%f\n' | sed 's/\.md$//'
      find "$PLAYBOOKS_DIR" -maxdepth 1 -mindepth 1 -type d -printf '%f\n'
    } | sort -u
  )
  echo
  echo "$END_MARKER"
} > "$TMP"

# Splice the new block into _base/README.md in place.
python3 - "$README" "$TMP" "$BEGIN_MARKER" "$END_MARKER" <<'PY'
import sys, pathlib

readme_path, new_block_path, begin, end = sys.argv[1:5]
readme = pathlib.Path(readme_path).read_text()
new_block = pathlib.Path(new_block_path).read_text().rstrip("\n")

start = readme.index(begin)
stop = readme.index(end) + len(end)
updated = readme[:start] + new_block + readme[stop:]

if updated != readme:
    pathlib.Path(readme_path).write_text(updated)
    print(f"updated {readme_path}")
else:
    print(f"no changes ({readme_path})")
PY
